agent_class: "FloatingRobotiq"
name: "floating_robotiq"
urdf_file: "floating_robotiq.urdf"
urdf_config:
  materials:
    gripper:
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
  links:
    left_inner_finger_pad:
      material: "gripper"
      patch_radius: 0.1
      min_patch_radius: 0.1
    right_inner_finger_pad:
      material: "gripper"
      patch_radius: 0.1
      min_patch_radius: 0.1
default_init_qpos: [0, 0]
default_control_mode: "pd_joint_delta_pos"
torque_freq: 10
cameras:
  - name: "hand_camera"
    mount: "camera_hand_link"
    hide_mount_link: true
    mount_p: [ 0,0,0 ]
    mount_q: [ 1,0,0,0 ]
    width: 256
    height: 144
    near: 0.1
    far: 2
    fx: 91.703
    fy: 91.746
    cx: 63.304
    cy: 36.884
    skew: 0
sensors:
  - name: "hand"
    mount: "camera_hand_link"
    rgb_resolution: [ 256, 144 ]
    ir_resolution: [ 256, 144 ]
    rgb_intrinsic: [[183.406, 0., 126.608], [0., 183.492, 73.768], [0., 0., 1.]]
    ir_intrinsic: [[183.406, 0., 126.608], [0., 183.491, 73.768], [0., 0., 1.]]
    trans_pose_l: [ -0.000258044, -0.0147611, -0.000184758, 9.99986449e-01, 5.69235052e-04, 1.23234267e-03, -5.02592655e-03 ]
    trans_pose_r: [ -1.21578e-05, -0.064705, -6.35905e-05, 9.99986449e-01, 5.69235052e-04, 1.23234267e-03, -5.02592655e-03 ]
    light_pattern_path: "descriptions/realsense2_description/d415-pattern-sq.png"
    max_depth: 2.0
    min_depth: 0.2
    max_disp: 64
    ir_ambient_strength: 0.002
    ir_light_dim_factor: 0.05
    ir_light_fov: 2.0
    ir_intensity: 5.0

controllers:
  pd_joint_delta_pos:
    - controller_type: "GripperPDJointPosMimicController"
      interpolate: false
      control_joints: [ 'robotiq_2f_140_left_driver_joint', 'robotiq_2f_140_right_driver_joint' ]
      controller_name: 'RobotiQMimic'
      joint_stiffness: 10000
      joint_damping: 100
      joint_friction: 0.2
      joint_force_limit: 10
      joint_pos_min: 0.0
      joint_pos_max: 0.068
